### ISSUE TITLE
How to add bignum support

### ISSUE THREAD

**Issue by Rudxain** [anguspmc/Collatz-Checker#1]
https://stackoverflow.com/a/21031196

So if you just want your code to run in Python v3, you don't need to import any library, just use the `//` operator when diving by 2, this ensures the compiler will always use arbitrary precision arithmetic, instead of defaulting to `float`s. This is weird because the modulo check explicitly proves that the number is even, but it seems the interpreter ignores this lol

**Comment by anguspmc** [comment]
Done, thanks!
