### ISSUE TITLE
Please add full int support

### ISSUE THREAD

**Issue by Rudxain** [anguspmc/Collatz-Checker#2]
According to [this article](https://en.wikipedia.org/wiki/Collatz_conjecture#Iterating_on_all_integers) you can check if `n` becomes -1, -5, and -17 (along with +1). You should also check 0, because any user could trigger an infinite loop that wastes CPU time. To check for all these numbers efficiently and easily, you should use a `Set` containing all these ints, like this:
```Python
cycles = {1, 0, -1, -5, -17}
print(n in cycles) #shows if `n` is any of those values
```

**Comment by anguspmc** [comment]
Thanks, added this in!
